version: 1.0

provider:
  name: openfaas
  gateway: http://openfaas.docker.localhost

functions:
  dummy-service:
    lang: dockerfile
    handler: ./services/dummy-service/
    image: gperreymond/dummy-service:latest
