faasnetes:
  readinessProbe:
    initialDelaySeconds: 0
    timeoutSeconds: 1
    periodSeconds: 1
  livenessProbe:
    initialDelaySeconds: 0
    timeoutSeconds: 1
    periodSeconds: 1
  functionNamespace: openfaas-fn
  gateway:
    replicas: 2
  queueWorker:
    replicas: 2
