functionNamespace: openfaas-fn

async: true

gateway:
  replicas: 2

ingress:
  enabled: true
  hosts:
  - host: openfaas.docker.localhost
    serviceName: gateway
    servicePort: 8080
    path: /
  annotations:
    kubernetes.io/ingress.class: nginx

faasnetes:
  readinessProbe:
    initialDelaySeconds: 0
    timeoutSeconds: 1
    periodSeconds: 1
  livenessProbe:
    initialDelaySeconds: 0
    timeoutSeconds: 1
    periodSeconds: 1

queueWorker:
  replicas: 2
