apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: grafana-ing
spec:
  rules:
  - host: grafana.docker.localhost
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 3000
        path: /
